name: Docker Build Workflow

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (for better build performance)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      # Step 4: Log in to Docker Hub (optional, if you want to push the image)
      # Set the DOCKER_USERNAME and DOCKER_PASSWORD secrets in GitHub repository settings
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build the Docker image using Docker Compose
      - name: Build and tag Docker image
        run: |
          docker-compose build

      # Step 6: Push Docker image to Docker Hub (optional)
      - name: Push Docker image to Docker Hub
        run: |
          docker-compose push
